name: Notion to Discord (Daily All Targets)

on:
  schedule:
    - cron: '0 23 * * *'  # JST 8:00（毎日）
  workflow_dispatch:

jobs:
  send-daily-message:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target: [paper, book, academic]

    # matrix.target を大文字にマップ（Actionsには upper() がないため三項で対応）
    env:
      TARGET_UPPER: ${{ matrix.target == 'paper' && 'PAPER' || matrix.target == 'book' && 'BOOK' || 'ACADEMIC' }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Set environment variables from secrets
        run: |
          echo "NOTION_API_KEY=${{ secrets.NOTION_API_KEY }}" >> $GITHUB_ENV
          echo "NOTION_VERSION=2022-06-28" >> $GITHUB_ENV
          echo "DISCORD_WEBHOOK_URL=${{ secrets[format('DISCORD_WEBHOOK_URL_%s', env.TARGET_UPPER)] }}" >> $GITHUB_ENV
          echo "NOTION_DATABASE_${{ matrix.target }}=${{ secrets[format('NOTION_DATABASE_%s', env.TARGET_UPPER)] }}" >> $GITHUB_ENV
          echo "MESSAGE_GREETING_${{ matrix.target }}=${{ secrets[format('MESSAGE_GREETING_%s', env.TARGET_UPPER)] }}" >> $GITHUB_ENV
          echo "SELECTED_PROPERTIES_${{ matrix.target }}=${{ secrets[format('SELECTED_PROPERTIES_%s', env.TARGET_UPPER)] }}" >> $GITHUB_ENV
          echo "MESSAGE_TEMPLATE={greeting}\\n{title}\\n{url}" >> $GITHUB_ENV

      - name: Run main.py for ${{ matrix.target }}
        run: python main.py ${{ matrix.target }}
