name: Notion to Discord (Daily All Targets)

on:
  schedule:
    - cron: '0 23 * * *'  # JST 8:00（毎日）
  workflow_dispatch:

jobs:
  send-daily-message:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # 実行引数 (paper, book, academic) を定義
        target: [paper, book, academic]

    # --- ▼ ここからが修正点 ▼ ---
    # すべてのシークレットを環境変数として「最初から」「すべて」定義する
    # これで main.py が自由に os.getenv(f"NOTION_DATABASE_{env_name.upper()}") できる
    env:
      # --- 共通シークレット ---
      NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
      NOTION_VERSION: 2022-06-28
      MESSAGE_TEMPLATE: "{greeting}\n{title}\n{url}" # ハードコードでOK
      
      # --- Paper ---
      NOTION_DATABASE_PAPER: ${{ secrets.NOTION_DATABASE_PAPER }}
      DISCORD_WEBHOOK_URL_PAPER: ${{ secrets.DISCORD_WEBHOOK_URL_PAPER }}
      MESSAGE_GREETING_PAPER: ${{ secrets.MESSAGE_GREETING_PAPER }}
      SELECTED_PROPERTIES_PAPER: ${{ secrets.SELECTED_PROPERTIES_PAPER }}

      # --- Book ---
      NOTION_DATABASE_BOOK: ${{ secrets.NOTION_DATABASE_BOOK }}
      DISCORD_WEBHOOK_URL_BOOK: ${{ secrets.DISCORD_WEBHOOK_URL_BOOK }}
      MESSAGE_GREETING_BOOK: ${{ secrets.MESSAGE_GREETING_BOOK }}
      SELECTED_PROPERTIES_BOOK: ${{ secrets.SELECTED_PROPERTIES_BOOK }}

      # --- Academic ---
      NOTION_DATABASE_ACADEMIC: ${{ secrets.NOTION_DATABASE_ACADEMIC }}
      DISCORD_WEBHOOK_URL_ACADEMIC: ${{ secrets.DISCORD_WEBHOOK_URL_ACADEMIC }}
      MESSAGE_GREETING_ACADEMIC: ${{ secrets.MESSAGE_GREETING_ACADEMIC }}
      SELECTED_PROPERTIES_ACADEMIC: ${{ secrets.SELECTED_PROPERTIES_ACADEMIC }}
    # --- ▲ ここまでが修正点 ▲ ---

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.9' # 3.9でもOK

      - name: Install dependencies
        run: pip install -r requirements.txt

      # 'Set environment variables' のステップは env ブロックに統合したため不要
      
      - name: Run main.py for ${{ matrix.target }}
        # matrix.target (paperなど) を引数として渡す
        run: python main.py ${{ matrix.target }}